name: learning
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+8 #ios
# version: 1.0.0+4 #android

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_doc_scanner: ^0.0.16
  flutter_localizations:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  #file
  path_provider: ^2.1.2
  file_picker: ^10.3.2
  open_filex: ^4.4.0

  uuid: ^4.5.1
  archive: ^4.0.7

  #local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  rx_shared_preferences: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #state management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  dartx: ^1.2.0
  equatable: ^2.0.7
  collection: ^1.19.1
  rxdart: ^0.27.7
  http_parser: ^4.1.2

  #responsive
  flutter_screenutil: ^5.9.0

  #dependency injection
  get_it: ^7.6.8
  injectable: ^2.4.1

  #access environment variables in .env file
  flutter_dotenv: ^5.1.0

  #generation models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  #talker & logger
  talker_flutter: 4.5.4
  talker_bloc_logger: ^4.1.3
  talker_dio_logger: ^4.1.3

  #restful api
  dio: ^5.4.2+1
  retrofit: ^4.1.0
  http: ^1.5.0

  result_dart: ^1.1.1
  intl: ^0.20.2

  #server datetime
  ntp: ^2.0.0

  #router
  auto_route: ^8.0.3
  mime: ^2.0.0
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  external_path: ^2.2.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  syncfusion_flutter_pdf: ^31.1.21
  pdfx: ^2.9.2
  url_launcher: ^6.3.2
  rate_my_app: ^2.3.2
  crypto: ^3.0.6
  awesome_snackbar_content: ^0.1.8
  flutter_slidable: ^4.0.3
  animated_reorderable_list: ^1.3.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.4.0
  intl_utils: ^2.8.7
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
